version: '3.8'

services:
   node_backend:
    container_name: node_tabnie
    image: node_tabnie:0.0.2
    build:
      context: .

    ports:
      - "3001:3001"

    environment:
      - EXTERNAL_PORT=3001
      - POSTGRES_DB_tabnie_db
    depends_on:
      - node_db
    node_db:
      container_name:node_db
      image:"postgres:12"
   